"""Output writer module for sqlseed.

Handles writing generated SQL seed scripts to stdout or a file,
with optional formatting and encoding control.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Optional


DEFAULT_ENCODING = "utf-8"
SQL_HEADER = "-- Generated by sqlseed\n-- Do not edit manually\n"
SQL_SEPARATOR = "\n" + "-" * 60 + "\n"


def build_output(sql: str, include_header: bool = True) -> str:
    """Wrap SQL content with an optional header comment.

    Args:
        sql: The raw SQL seed script.
        include_header: Whether to prepend the standard header.

    Returns:
        Final output string ready to be written.
    """
    if include_header:
        return SQL_HEADER + SQL_SEPARATOR + sql.strip() + "\n"
    return sql.strip() + "\n"


def write_to_file(content: str, path: str, encoding: str = DEFAULT_ENCODING) -> None:
    """Write content to a file, creating parent directories if needed.

    Args:
        content: The string content to write.
        path: Destination file path.
        encoding: File encoding (default utf-8).

    Raises:
        OSError: If the file cannot be written.
    """
    dest = Path(path)
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(content, encoding=encoding)


def write_to_stdout(content: str) -> None:
    """Write content to standard output.

    Args:
        content: The string content to print.
    """
    sys.stdout.write(content)


def write_output(
    sql: str,
    output_path: Optional[str] = None,
    include_header: bool = True,
    encoding: str = DEFAULT_ENCODING,
) -> None:
    """Build and dispatch SQL output to file or stdout.

    Args:
        sql: The raw SQL seed script.
        output_path: If provided, write to this file path; otherwise stdout.
        include_header: Whether to include the standard header comment.
        encoding: Encoding used when writing to a file.
    """
    content = build_output(sql, include_header=include_header)
    if output_path:
        write_to_file(content, output_path, encoding=encoding)
    else:
        write_to_stdout(content)
